CFLAGS=-O # -DLITTLE_ENDIAN
all: des descert certify

des: main.o des.o getpass.o misc.o
	cc -o des main.o des.o getpass.o misc.o

descert: descert.o des.o
	cc -o descert descert.o des.o

certify: descert testdata
	descert < testdata
	touch certify
